### ISSUE TITLE
Can't compile on Ubuntu 14.10

### ISSUE THREAD

**Issue by ccharlot** [pfps/yoga-laptop#31]
Hi !

Here is the result I get : 

christophe@Lenovo-Yoga-2-Pro:~/Apps/yoga-laptop$ make sensors-drivers
cd sensors/drivers && make default
make[1]: Entering directory '/home/christophe/Apps/yoga-laptop/sensors/drivers'
make -C /usr/src/linux-headers-3.16.0-30-generic SUBDIRS=/home/christophe/Apps/yoga-laptop/sensors/drivers modules
make[2]: Entering directory '/usr/src/linux-headers-3.16.0-30-generic'
  CC [M]  /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o
/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.c: In function ‘hid_sensor_data_rdy_trigger_set_state’:
/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.c:56:17: error: incompatible types when assigning to type ‘atomic_t’ from type ‘bool’
  st->data_ready = state;
                 ^
scripts/Makefile.build:263: recipe for target '/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o' failed
make[3]: *** [/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o] Error 1
Makefile:1345: recipe for target '_module_/home/christophe/Apps/yoga-laptop/sensors/drivers' failed
make[2]: *** [_module_/home/christophe/Apps/yoga-laptop/sensors/drivers] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-3.16.0-30-generic'
Makefile:22: recipe for target 'default' failed
make[1]: *** [default] Error 2
make[1]: Leaving directory '/home/christophe/Apps/yoga-laptop/sensors/drivers'
Makefile:15: recipe for target 'sensors-drivers' failed
make: *** [sensors-drivers] Error 2

Any idea what I'm doing wrong ?

**Comment by pfps** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I just recompiled and I get this too.

I expect that some type has changed in the underlying IIO system.

peter


On 02/08/2015 02:37 AM, ccharlot wrote:
> Hi !
> 
> Here is the result I get :
> 
> christophe@Lenovo-Yoga-2-Pro:~/Apps/yoga-laptop$ make sensors-drivers cd
> sensors/drivers && make default make[1]: Entering directory
> '/home/christophe/Apps/yoga-laptop/sensors/drivers' make -C
> /usr/src/linux-headers-3.16.0-30-generic 
> SUBDIRS=/home/christophe/Apps/yoga-laptop/sensors/drivers modules 
> make[2]: Entering directory '/usr/src/linux-headers-3.16.0-30-generic' CC
> [M]
> /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o 
> /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.c:
> In function ‘hid_sensor_data_rdy_trigger_set_state’: 
> /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.c:56:17:
>
> 
error: incompatible types when assigning to type ‘atomic_t’ from type ‘bool’
> st->data_ready = state; ^ scripts/Makefile.build:263: recipe for target 
> '/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o'
> failed make[3]: *** 
> [/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o]
> Error 1 Makefile:1345: recipe for target 
> '/module//home/christophe/Apps/yoga-laptop/sensors/drivers' failed 
> make[2]: *** [/module//home/christophe/Apps/yoga-laptop/sensors/drivers]
> Error 2 make[2]: Leaving directory
> '/usr/src/linux-headers-3.16.0-30-generic' Makefile:22: recipe for target
> 'default' failed make[1]: *** [default] Error 2 make[1]: Leaving
> directory '/home/christophe/Apps/yoga-laptop/sensors/drivers' 
> Makefile:15: recipe for target 'sensors-drivers' failed make: ***
> [sensors-drivers] Error 2
> 
> Any idea what I'm doing wrong ?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/pfps/yoga-laptop/issues/31>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJU134rAAoJECjN6+QThfjzOHIIAKvk9z9QftaPXjgno9o3hfRM
uraNh7q/QleV26kLeG5vPxYvDpxS5sX/IfEHcRjDlpZioBspJtL96R5O4c92hIdP
WGvFyGN5miYngcj1a/E2rbWb8NaJ059BnegcG+bYkVbRbwwHMYFl5UY8EnjNMDt7
ePMJUgUput2Pqztl6gfpGOE/KYrrRlIpz6FA6fu8GGeU9BJwT+2w1Uu152JhsQ1w
rPv2RvSuvSd9ckxMff+iHeKHTVnaWMcVzX76EM6Jkyv0rnGRsUlZF6O4a4/+sRG5
3iqwY2emkZyod7SghKJZZEEGNtxM6l7j5B+6EM0VomlKGuM8KE94ICzM8H+rTC0=
=N7tT
-----END PGP SIGNATURE-----

**Comment by pfps** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

The drivers are included in the distribution because older kernels did not
have the necessary patches.   As current kernels should have everything
needed, these drivers are not needed any more.

You can get around the problem by doing
  make ideadpad-laptop
  make programs

instead.

peter


On 02/08/2015 02:37 AM, ccharlot wrote:
> Hi !
> 
> Here is the result I get :
> 
> christophe@Lenovo-Yoga-2-Pro:~/Apps/yoga-laptop$ make sensors-drivers cd
> sensors/drivers && make default make[1]: Entering directory
> '/home/christophe/Apps/yoga-laptop/sensors/drivers' make -C
> /usr/src/linux-headers-3.16.0-30-generic 
> SUBDIRS=/home/christophe/Apps/yoga-laptop/sensors/drivers modules 
> make[2]: Entering directory '/usr/src/linux-headers-3.16.0-30-generic' CC
> [M]
> /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o 
> /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.c:
> In function ‘hid_sensor_data_rdy_trigger_set_state’: 
> /home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.c:56:17:
>
> 
error: incompatible types when assigning to type ‘atomic_t’ from type ‘bool’
> st->data_ready = state; ^ scripts/Makefile.build:263: recipe for target 
> '/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o'
> failed make[3]: *** 
> [/home/christophe/Apps/yoga-laptop/sensors/drivers/hid-sensor-trigger.o]
> Error 1 Makefile:1345: recipe for target 
> '/module//home/christophe/Apps/yoga-laptop/sensors/drivers' failed 
> make[2]: *** [/module//home/christophe/Apps/yoga-laptop/sensors/drivers]
> Error 2 make[2]: Leaving directory
> '/usr/src/linux-headers-3.16.0-30-generic' Makefile:22: recipe for target
> 'default' failed make[1]: *** [default] Error 2 make[1]: Leaving
> directory '/home/christophe/Apps/yoga-laptop/sensors/drivers' 
> Makefile:15: recipe for target 'sensors-drivers' failed make: ***
> [sensors-drivers] Error 2
> 
> Any idea what I'm doing wrong ?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/pfps/yoga-laptop/issues/31>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJU14E8AAoJECjN6+QThfjzMncIAKk1KG1R2SRU0IYMVHyjvYly
456YZEDOFE0rEvwiufU92o6xWBlwxFmw9Tpj/HDVIZVrUPZBZ7oTMqaro7L1pcur
pPqcanez+JCQXR4d+tEQrwoJYu2BQfVsdjfEm5cXHMeu+ej0z56IDzDCmjTdnK2F
HXet0UPppFP3/7GBsheBEkqNjJxgNA4wifnjUGCISqQfoKUDYBwkrDJY5XC53UkC
ULK1/Dhw0BDf4g7dFU7Nx5wgfjDautx//9oEtjRj8u8cY4SQNofUOLgEib9042yv
sokPMm1d2H93jge8HH1EpDQsRTHSsJAsOlTz9gxtMkDjOsf4IjqsY/99X+ZdHCY=
=oO2Q
-----END PGP SIGNATURE-----

**Comment by pfps** [comment]
I pushed a change to the makefile and documentation that describes the current situation.

**Comment by ccharlot** [comment]
Thanks !

It works just perfectly now.

Christophe
